"""initial structure

Revision ID: ac204abbae52
Revises: 
Create Date: 2025-12-20 17:15:08.774912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac204abbae52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=255), nullable=False),
    sa.Column('guild_icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_index(op.f('ix_guilds_guild_id'), 'guilds', ['guild_id'], unique=False)
    op.create_index(op.f('ix_guilds_guild_name'), 'guilds', ['guild_name'], unique=False)
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('global_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_global_name'), 'users', ['global_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('favourite_playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('uploader', sa.String(length=100), nullable=True),
    sa.Column('added_in', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_favourite_playlist_user_url')
    )
    op.create_index(op.f('ix_favourite_playlists_url'), 'favourite_playlists', ['url'], unique=False)
    op.create_index(op.f('ix_favourite_playlists_user_id'), 'favourite_playlists', ['user_id'], unique=False)
    op.create_table('favourite_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('uploader', sa.String(length=100), nullable=True),
    sa.Column('added_in', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_favourite_track_user_url')
    )
    op.create_check_constraint(
        "ck_favourite_playlists_count_ge_1",
        "favourite_playlists",
        "count >= 1",
    )
    op.create_index(op.f('ix_favourite_tracks_url'), 'favourite_tracks', ['url'], unique=False)
    op.create_index(op.f('ix_favourite_tracks_user_id'), 'favourite_tracks', ['user_id'], unique=False)
    op.create_table('guild_admins',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('guild_blacklist',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('guild_config',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('auto_role_active', sa.Boolean(), nullable=False),
    sa.Column('auto_role_id', sa.Integer(), nullable=True),
    sa.Column('auto_role_name', sa.String(length=255), nullable=True),
    sa.Column('welcome_active', sa.Boolean(), nullable=False),
    sa.Column('welcome_channel_id', sa.Integer(), nullable=True),
    sa.Column('welcome_channel_name', sa.String(length=255), nullable=True),
    sa.Column('welcome_embed_title', sa.String(length=255), nullable=True),
    sa.Column('welcome_embed_description', sa.String(length=255), nullable=True),
    sa.Column('welcome_embed_colour', sa.String(length=7), nullable=True),
    sa.Column('welcome_show_pfp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_check_constraint(
        "ck_guild_config_welcome_show_pfp_range",
        "guild_config",
        "welcome_show_pfp >= 0 AND welcome_show_pfp <= 2",
    )
    op.create_index(op.f('ix_guild_config_auto_role_id'), 'guild_config', ['auto_role_id'], unique=False)
    op.create_index(op.f('ix_guild_config_welcome_channel_id'), 'guild_config', ['welcome_channel_id'], unique=False)
    op.create_table('guild_members',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('user_config',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('translate_private', sa.Boolean(), nullable=False),
    sa.Column('fact_check_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_config')
    op.drop_table('guild_members')
    op.drop_index(op.f('ix_guild_config_welcome_channel_id'), table_name='guild_config')
    op.drop_index(op.f('ix_guild_config_auto_role_id'), table_name='guild_config')
    op.drop_table('guild_config')
    op.drop_table('guild_blacklist')
    op.drop_table('guild_admins')
    op.drop_index(op.f('ix_favourite_tracks_user_id'), table_name='favourite_tracks')
    op.drop_index(op.f('ix_favourite_tracks_url'), table_name='favourite_tracks')
    op.drop_table('favourite_tracks')
    op.drop_index(op.f('ix_favourite_playlists_user_id'), table_name='favourite_playlists')
    op.drop_index(op.f('ix_favourite_playlists_url'), table_name='favourite_playlists')
    op.drop_table('favourite_playlists')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_global_name'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('owners')
    op.drop_index(op.f('ix_guilds_guild_name'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_guild_id'), table_name='guilds')
    op.drop_table('guilds')
    # ### end Alembic commands ###
